### ISSUE TITLE
Anonymous access to WMS returns exception

### ISSUE THREAD

**Issue by jsanchezkzs** [GeoNode/geoserver-docker#65]
Hi,

I'm trying to use Geoserver as a Docker service. My porblem is that when I'm not logged into Geoserver Administration panel I can't access to my Data through WMS.

Using the OpenLayers preview for example : 
`http://localhost:8080/geoserver/geonode/wms?service=WMS&version=1.1.0&request=GetMap&layers=geonode%3Aplanet_osm_line&bbox=636091.0%2C5645585.5%2C640413.4375%2C5653261.5&width=432&height=768&srs=EPSG%3A3857&format=application/openlayers`

I get this error :
````xml
<ServiceExceptionReport version="1.1.1">
    <ServiceException code="LayerNotDefined" locator="layers">
        Could not find layer geonode:planet_osm_line
    </ServiceException>
</ServiceExceptionReport>
````

Here's the [complete log](https://github.com/GeoNode/geoserver-docker/files/4493242/geoserver.log) I dumped when error occured (2.16.2)

I tried 
 - To change security configuration (Service and Layers configurations. But not both at the same time, as documentation says)
 - Multiple versions (2.16.2 and 2.15.4)

But couldn't manage to make it work.

The only way for me to make this work was to run the [Binary](http://geoserver.org/download/) that can be found on Geoserver website. (I also tried two version, 2.16.2 and 2.17-RC). It worked without any security configuration. Importing data the same way as with Docker versions.

Has anyone been in the same situation ?

PS: Data has been imported to a Docker PostGIS using osm2pgsql.

**Comment by bytesnz** [comment]
Just been pulling my hair out by the same issue I think. I have just been trying different docker containers and different data and have noticed that the unautorized access doesn't work with the standard data from https://build.geo-solutions.it/geonode/geoserver/latest/ (data-2.17.1.zip), but it does when starting with the osgeolive version (data-2.17.1-osgeolive.zip).

Reproduction steps:
1. download and unzip data from https://build.geo-solutions.it/geonode/geoserver/latest/
1. Start the docker container
```
docker run --name geoserver --rm -it -p 8080:8080 -v $(pwd)/data:/geoserver_data/data geonode/geoserver:2.17.1
```
1. Log in to the interface
1. Create a new by importing data (tried using https://github.com/danwild/leaflet-geotiff-2/tree/master/demo)
1. See if layer is visible in Layer Preview as anonymous user
1. See if layer preview works

I did notice that the layers are pulled down the web ui, but they aren't display (not the layer totals in image below)
![image](https://user-images.githubusercontent.com/1755886/89181790-4b149800-d58c-11ea-9205-ca23be7060b8.png)

I tried doing a diff on the data directories using meld, but nothing sang out apart from data was missing csw.xml file. Adding it made no change. The osgeolive version continued to work after deleting the workspaces included in the data, so that might be a workaround for now?

Did you get anywhere?

**Comment by t-book** [comment]
@bytesnz you know that this is a geoserver build for geonode?

**Comment by bytesnz** [comment]
Yes..? Does that mean it shouldn't work following the [quick start](https://github.com/GeoNode/geoserver-docker#quick-start)?

**Comment by polzader** [comment]
Is it possible to use this image without geonode? Is it possible to enable access to anonymous users?
I have this image but I don't use geonode, I want to use geoserver independently.

**Comment by gannebamm** [comment]
@polzader You can just use the officlial GeoServer docker image if you do not need GeoNode:
https://hub.docker.com/r/geosolutionsit/geoserver

Or take one of the other huge geospatial companie ones, like kartoza and terrestris:
https://hub.docker.com/r/kartoza/geoserver
https://hub.docker.com/r/terrestris/geoserver

**Comment by polzader** [comment]
Yes, thanks. but I already have the geonode / geoserver image integrated into my project and I only need to enable ANONYMOUS access to the layers. Could you help me? Could you try disabling GeoFence? Or maybe the solution is another way?

**Comment by t-book** [comment]
@polzader super easy, just create a role that allowes all ;)

https://docs.geoserver.org/latest/en/user/_images/tutorial_rulespage2.png

You would choose allow instead of deny

https://docs.geoserver.org/latest/en/user/community/geofence-server/index.html

**Comment by afabiani** [comment]
Also you could:

1. Create a geofence rule to `allow all` to anything
2. Set this option [here](https://docs.geonode.org/en/master/basic/settings/index.html#geofence-security-enabled) of GeoNode to `False`

**Comment by polzader** [comment]
Thanks @t-book  and @afabiani . It now Work!

The problem I had was that, add the rules in geofence  and at the same time, check the option "Use GeoServer roles to obtain authorizations "in" GeoFence Administration Page" which causes conflict and geofence rules stop working.

This ticket can be closed.
